/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: 'affichage_gps' 
 * Target:  'Target_1' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* Keil::Device:STM32Cube HAL:Common@1.3.0 */
#define USE_HAL_DRIVER


#endif /* PRE_INCLUDE_GLOBAL_H */
