/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: 'affichage_gps' 
 * Target:  'Target_1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32f7xx.h"

/* Keil::CMSIS Driver:CAN@1.15.0 */
#define RTE_Drivers_CAN1                /* Driver CAN1 */
#define RTE_Drivers_CAN2                /* Driver CAN2 */
#define RTE_Drivers_CAN3                /* Driver CAN3 */
/* Keil::Device:STM32Cube Framework:Classic@1.3.0 */
#define RTE_DEVICE_FRAMEWORK_CLASSIC
/* Keil::Device:STM32Cube HAL:CAN@1.3.0 */
#define RTE_DEVICE_HAL_CAN
/* Keil::Device:STM32Cube HAL:Common@1.3.0 */
#define RTE_DEVICE_HAL_COMMON
/* Keil::Device:STM32Cube HAL:Cortex@1.3.0 */
#define RTE_DEVICE_HAL_CORTEX
/* Keil::Device:STM32Cube HAL:DMA2D@1.3.0 */
#define RTE_DEVICE_HAL_DMA2D
/* Keil::Device:STM32Cube HAL:DMA@1.3.0 */
#define RTE_DEVICE_HAL_DMA
/* Keil::Device:STM32Cube HAL:GPIO@1.3.0 */
#define RTE_DEVICE_HAL_GPIO
/* Keil::Device:STM32Cube HAL:I2C@1.3.0 */
#define RTE_DEVICE_HAL_I2C
/* Keil::Device:STM32Cube HAL:LTDC@1.3.0 */
#define RTE_DEVICE_HAL_LTDC
/* Keil::Device:STM32Cube HAL:PWR@1.3.0 */
#define RTE_DEVICE_HAL_PWR
/* Keil::Device:STM32Cube HAL:RCC@1.3.0 */
#define RTE_DEVICE_HAL_RCC
/* Keil::Device:STM32Cube HAL:SDRAM@1.3.0 */
#define RTE_DEVICE_HAL_SDRAM
/* Keil::Device:STM32Cube HAL:UART@1.3.0 */
#define RTE_DEVICE_HAL_UART
/* Keil::Device:Startup@1.2.5 */
#define RTE_DEVICE_STARTUP_STM32F7XX    /* Device Startup for STM32F7 */


#endif /* RTE_COMPONENTS_H */
