/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: 'liquid_sensor' 
 * Target:  'Target_1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32f4xx.h"

/* ARM::CMSIS:RTOS2:Keil RTX5&Source@5.9.0 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
#define RTE_CMSIS_RTOS2_RTX5            /* CMSIS-RTOS2 Keil RTX5 */
#define RTE_CMSIS_RTOS2_RTX5_SOURCE     /* CMSIS-RTOS2 Keil RTX5 Source */
/* Keil::CMSIS Driver:CAN@1.17 */
#define RTE_Drivers_CAN1                /* Driver CAN1 */
#define RTE_Drivers_CAN2                /* Driver CAN2 */
#define RTE_Drivers_CAN3                /* Driver CAN3 */
/* Keil::Device:STM32Cube Framework:Classic@1.8.1 */
#define RTE_DEVICE_FRAMEWORK_CLASSIC
/* Keil::Device:STM32Cube HAL:ADC@1.8.1 */
#define RTE_DEVICE_HAL_ADC
/* Keil::Device:STM32Cube HAL:Common@1.8.1 */
#define RTE_DEVICE_HAL_COMMON
/* Keil::Device:STM32Cube HAL:Cortex@1.8.1 */
#define RTE_DEVICE_HAL_CORTEX
/* Keil::Device:STM32Cube HAL:DAC@1.8.1 */
#define RTE_DEVICE_HAL_DAC
/* Keil::Device:STM32Cube HAL:DMA@1.8.1 */
#define RTE_DEVICE_HAL_DMA
/* Keil::Device:STM32Cube HAL:GPIO@1.8.1 */
#define RTE_DEVICE_HAL_GPIO
/* Keil::Device:STM32Cube HAL:PWR@1.8.1 */
#define RTE_DEVICE_HAL_PWR
/* Keil::Device:STM32Cube HAL:RCC@1.8.1 */
#define RTE_DEVICE_HAL_RCC
/* Keil::Device:STM32Cube LL:ADC@1.8.1 */
#define RTE_DEVICE_LL_ADC
/* Keil::Device:STM32Cube LL:Common@1.8.1 */
#define RTE_DEVICE_LL_COMMON
/* Keil::Device:STM32Cube LL:PWR@1.8.1 */
#define RTE_DEVICE_LL_PWR
/* Keil::Device:STM32Cube LL:RCC@1.8.1 */
#define RTE_DEVICE_LL_RCC
/* Keil::Device:STM32Cube LL:UTILS@1.8.1 */
#define RTE_DEVICE_LL_UTILS
/* Keil::Device:Startup@2.6.3 */
#define RTE_DEVICE_STARTUP_STM32F4XX    /* Device Startup for STM32F4 */


#endif /* RTE_COMPONENTS_H */
